apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../overlays/istio

# Optional: customize namespace
# namespace: my-namespace

# Optional: add name prefix for env-specific deployments
# namePrefix: dev-