apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  gateway.llm-d.ai/provider: gke

patches:
  # Update gateway class to GKE
  - patch: |-
      - op: replace
        path: /spec/gatewayClassName
        value: gke-l7-regional-external-managed
    target:
      kind: Gateway
      name: llm-d-gateway